# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-01-09 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Mobile', models.BigIntegerField()),
                ('ratting', models.IntegerField()),
                ('Data', models.DateTimeField()),
                ('Feedback', models.CharField(max_length=100)),
            ],
        ),
    ]
