# Generated by Django 3.0 on 2020-02-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dairy_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, null=True)),
                ('Description', models.CharField(max_length=200, null=True)),
                ('UploadSelfie', models.ImageField(blank=True, upload_to='content/')),
                ('UploadImage1', models.ImageField(blank=True, upload_to='content/')),
                ('UploadImage2', models.ImageField(blank=True, upload_to='content/')),
                ('UploadImage3', models.ImageField(blank=True, upload_to='content/')),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
