# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-01-27 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OneToOneApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondata',
            name='CompanyDatahere',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='OneToOneApp.CompanyData'),
        ),
    ]
