# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-01-27 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneToOneApp', '0003_auto_20200127_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondata',
            name='CompanyDatahere',
            field=models.OneToOneField(null=True, on_delete=models.SET(3), to='OneToOneApp.CompanyData'),
        ),
    ]
