# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-01-27 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OneToOneApp', '0004_auto_20200127_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondata',
            name='CompanyDatahere',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OneToOneApp.CompanyData'),
        ),
    ]
