# Generated by Django 3.0 on 2020-01-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Mobile', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=100)),
                ('Salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProxyDatabase',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('proxyApp.employeedatabase',),
        ),
    ]
