# Generated by Django 3.0 on 2020-02-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelFormApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_model',
            name='pic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
