# Generated by Django 3.0 on 2020-02-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelFormApp', '0003_auto_20200217_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_model',
            name='Customer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer_model',
            name='Email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer_model',
            name='Location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer_model',
            name='Mobile_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customer_model',
            name='Sales',
            field=models.IntegerField(),
        ),
    ]
