# Generated by Django 3.0 on 2020-02-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelFormApp', '0005_remove_customer_model_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_model',
            name='picture',
            field=models.ImageField(blank=True, max_length=10, upload_to='content/'),
        ),
    ]
