# Generated by Django 3.0 on 2020-01-30 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDatabase',
            fields=[
                ('Cid', models.AutoField(primary_key=True, serialize=False)),
                ('CName', models.CharField(max_length=100)),
                ('Sales', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDatabase',
            fields=[
                ('Eid', models.AutoField(primary_key=True, serialize=False)),
                ('EName', models.CharField(max_length=100)),
                ('Salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentDatabase',
            fields=[
                ('customerdatabase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='MultipalApp.CustomerDatabase')),
                ('employeedatabase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='MultipalApp.EmployeeDatabase')),
                ('Sid', models.AutoField(primary_key=True, serialize=False)),
                ('SName', models.CharField(max_length=100)),
                ('Marks', models.IntegerField()),
            ],
            bases=('MultipalApp.employeedatabase', 'MultipalApp.customerdatabase'),
        ),
    ]
