# Generated by Django 3.0 on 2020-01-30 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EName', models.CharField(max_length=100)),
                ('Salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDatabase',
            fields=[
                ('employeedatabase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MultiLevelApp.EmployeeDatabase')),
                ('CName', models.CharField(max_length=100)),
                ('Sales', models.IntegerField()),
            ],
            bases=('MultiLevelApp.employeedatabase',),
        ),
        migrations.CreateModel(
            name='StudentDatabase',
            fields=[
                ('customerdatabase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MultiLevelApp.CustomerDatabase')),
                ('SName', models.CharField(max_length=100)),
                ('Marks', models.IntegerField()),
            ],
            bases=('MultiLevelApp.customerdatabase',),
        ),
    ]
