# Generated by Django 3.0 on 2020-02-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentdatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_number', models.IntegerField()),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('School_name', models.CharField(max_length=100)),
                ('Class_name', models.CharField(max_length=100)),
                ('Section_name', models.CharField(max_length=100)),
                ('Telugu_marks', models.IntegerField()),
                ('Hind_marks', models.IntegerField()),
                ('English_marks', models.IntegerField()),
                ('Maths_marks', models.IntegerField()),
                ('Science_marks', models.IntegerField()),
                ('Social_marks', models.IntegerField()),
            ],
        ),
    ]
