# Generated by Django 3.0 on 2020-02-12 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Curd_Operation_StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdatabase',
            old_name='Hind_marks',
            new_name='Hindi_marks',
        ),
    ]
